# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ./annotation-processor/build
            ./compiler-plugin/build
            ./gradle-plugin/build
            ./buildSrc/build
            ./idea-plugin/build
            ./benchmarks/build
            ./lib/build
            ./compiler-plugin-embeddable/build
            ./build
            ./annotation-value-gen/build
          key: ${{ runner.os }}
      - name: Build with Gradle
        run: ./gradlew build
      - name: Check with Plugin Verifier
        run: ./gradlew runPluginVerifier
      - name: stop daemon
        run: ./gradlew --stop
